[toolchain]
anchor_version = "0.29.0"
solana_version = "1.17.10"

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_faucet = "CCyXskW2kpYFHtLnJ8i8RNKJazD871iq3FhRSkbztjTm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
