[toolchain]
anchor_version = "0.29.0"
solana_version = "1.16.20"

[features]
seeds = false
skip-lint = false

[programs.localnet]
spl_faucet = "GLAiyTqs45dw1Nm1WtxLYorPaE9j38EP1T3CJaf1AuQX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
