name: Publish NPM Package

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  SOLANA_VERSION: stable
  ANCHOR_VERSION: 0.29.0

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup | Rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy

      - name: Add Rust to PATH
        run: |
          echo "/home/runner/.cargo/bin" >> $GITHUB_PATH

      - name: Install solana
        run: curl -sSfL https://release.solana.com/$SOLANA_VERSION/install | sh

      - name: Add Solana to PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor
        run: npm i -g @coral-xyz/anchor-cli@$ANCHOR_VERSION

      - name: Run Anchor Build
        run: anchor build --arch sbf

      - name: Install NPM Packages
        uses: borales/actions-yarn@v4
        with:
          cmd: install --frozen-lockfile

      - name: Build TypeScript
        uses: borales/actions-yarn@v4
        with:
          cmd: build

      - name: Publish SDK
        run: |
          echo '//registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}}' > .npmrc
          npm publish --access public
